version: '2'
services:
  allinone:
    cap_add:
    - SYS_ADMIN
    - NET_ADMIN
    - SYS_PTRACE
    - IPC_LOCK
    image: 10.1.127.3:5000/neuvector/allinone:jenkins-nv-build-allinone-1266
    environment:
      CLUSTER_JOIN_ADDR: allinone
      CTRL_PATH_DEBUG: '1'
    security_opt:
    - apparmor:unconfined
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /proc:/host/proc:ro
    - /sys/fs/cgroup:/host/cgroup:ro
    - /var/neuvector:/var/neuvector
    ports:
    - 8443:8443/tcp
    - 443:443/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: nvallinone=true
      io.rancher.scheduler.global: 'true'
