name: Neuvector Allinone
description: |
  Neuvector Allinone Stack
version: 0
category: Security
maintainer: Kevin Li
license: 
projectURL: https://github.com/kevinl94303/Rancher-Catalog-Neuvector-Allinone/
